ArtifactID:1414769 Comment:Created scripts to enable the openhpi daemon to run as a service.

diff --git a/openhpi/trunk/openhpid2/openhpid.sh.in b/openhpi/trunk/openhpid2/openhpid.sh.in
--- a/openhpi/trunk/openhpid2/openhpid.sh.in
+++ b/openhpi/trunk/openhpid2/openhpid.sh.in
@@ -8,33 +8,166 @@
 # processname: openhpid
 # config: the standard openhpi conf file specified on the command line or the env.
 # pidfile: /var/run/openhpid.pid
+# 
+# Author(s):
+#	W. David Ashley <dashley@us.ibm.com>
+#	Daniel de Araujo <ddearauj@us.ibm.com>
 
 # Source function library.
-. /etc/init.d/functions
-
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
 prog="openhpid"
+
+# Determine whether the lsb package is installed
+# If it is, determine which lsb in installed:
+# redhat, suse, or standard lsb
+
+if test -f /etc/init.d/functions
+then
+   lsbtype="rh"
+   . /etc/init.d/functions
+elif test -f /etc/rc.status
+then
+   lsbtype="suse"
+   . /etc/rc.status
+elif test -f /lib/lsb/init-functions
+then
+   lsbtype="lsb"
+   . /lib/lsb/init-functions
+else
+   lsbtype="nolsb"
+fi
+
+print_outcome()
+{
+   
+	case "${lsbtype}" in
+      
+		rh)
+   			echo
+   			[ "$?" -eq 0 ]
+   			;;
+
+		suse)
+ 			rc_status @prefix@/sbin/openhpid
+			;;
+
+		lsb)
+			if test "$?" -eq 0
+   			then
+      				log_success_msg "success"
+   			else
+				log_failure_msg "failed"
+   			fi
+  			;;
+   
+		nolsb)
+			if test "$?" -eq 0
+			then
+				echo " ... success"
+			fi
+			if test "$?" -ne 0
+			then
+				echo " ... failed"
+			fi
+			;;
+   	esac
+}
 
 start() {
         export `@prefix@/bin/openhpi-switcher --env=standard` || return 1
-	echo -n $"Starting $prog: "
-	daemon @prefix@/bin/openhpid -c @CONFPATH@/@HPI_PKG@.conf
-	RETVAL=$?
-	echo
-	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/openhpid
-	return $RETVAL
+	echo $"Starting $prog: "
+	case "${lsbtype}" in
+		
+		rh) 
+			daemon @prefix@/sbin/openhpid -c @CONFPATH@/@HPI_PKG@.conf
+			RETVAL=$?
+			;;
+		suse)
+			startproc @prefix@/sbin/openhpid -c @CONFPATH@/@HPI_PKG@.conf
+			RETVAL=$?
+			;;
+		lsb)
+			start_daemon @prefix@/sbin/openhpid -c @CONFPATH@/@HPI_PKG@.conf
+			RETVAL=$?
+			;;
+		nolsb)
+			@prefix@/sbin/openhpid -c @CONFPATH@/@HPI_PKG@.conf
+			RETVAL=$?
+			;;
+			
+	esac
+
+	print_outcome
+
 }
 
 stop() {
-	echo -n $"Stopping $prog: "
-	killproc openhpid
-	RETVAL=$?
-	echo
-	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/openhpid
-	return $RETVAL
+	echo $"Stopping $prog: "
+	
+	case "${lsbtype}" in
+		
+		rh | lsb | suse)
+			killproc @prefix@/sbin/openhpid
+			RETVAL=$?
+			;;
+		
+		nolsb)
+			if test -f /var/run/openhpid.pid && test "`cat /var/run/openhpid.pid`" != ""
+         		then
+            			kill "`cat /var/run/openhpid.pid`"
+				RETVAL=$?  
+			else
+				RETVAL=0
+			fi	          
+			;;
+		
+	esac
+	
+	if test "$RETVAL" -eq 0 && test -f /var/run/openhpid.pid
+	then
+		rm -f /var/lock/openhpid
+		rm -f /var/run/openhpid.pid
+	fi	
+
 }	
 
-rhstatus() {
-	status @prefix@/bin/openhpid
+dstatus() {
+	echo $"Checking for $prog daemon: "
+	
+	case "${lsbtype}" in
+		
+		rh) 
+			status @prefix@/sbin/openhpid
+			;;
+		suse)
+			checkproc @prefix@/sbin/openhpid
+			rc_status -v
+			;;
+		lsb)
+			pid="`pidofproc @prefix@/sbin/openhpid`"
+         		if test "${pid}" != ""
+			then
+				log_success_msg "$prog is running"
+			else
+				log_success_msg "$prog is not running"	
+			fi	
+			;;
+		nolsb)
+			if test -f /var/run/openhpid.pid && 
+				test "`cat /var/run/openhpid.pid`" != "" && 
+				kill -0 "`cat /var/run/openhpid.pid`"
+			then
+				echo "$prog is running"
+			else
+				echo "$prog is not running"
+			fi		
+			
+			;;
+			
+	esac	
+	
+
+
 }	
 
 restart() {
@@ -61,7 +194,7 @@ case "$1" in
   	restart
 	;;
   status)
-  	rhstatus
+  	dstatus
 	;;
   force-reload)
   	force-reload
