Adding an early draft of a plug-in that translates sysfs info into HPI.  This check-in will create an RPT entry for the system board, and add RDR's for any ADM1021 i2c devices found.  It shouldn't be difficult to add support for other nuggets extracted out of sysfs.
I enabled the ADM1021 just because that's what showed up in sysfs on my
Dell workstation, and I didn't want to check-in code I couldn't test.

diff --git a/openhpi/trunk/configure.in b/openhpi/trunk/configure.in
--- a/openhpi/trunk/configure.in
+++ b/openhpi/trunk/configure.in
@@ -30,6 +30,7 @@ AC_PROG_RANLIB
 dnl Check fo libraries
 have_uuid=no
 have_openipmi=no
+have_sysfs=no
 
 AC_CHECK_LIB([glib], [g_slist_alloc], 
     [
@@ -54,6 +55,8 @@ AC_CHECK_LIB([ltdl], [lt_dlopen], [], [
     ])
 
 AC_CHECK_LIB([OpenIPMI], [ipmi_smi_setup_con], [have_openipmi=yes])
+
+AC_CHECK_LIB([sysfs], [sysfs_get_mnt_path], [have_sysfs=yes])
 
 AC_CHECK_LIB([uuid], [uuid_generate], [have_uuid=yes], [
     echo "************************************************************"
@@ -128,6 +131,21 @@ AC_ARG_ENABLE([ipmi],
         fi
     fi])
 
+AC_ARG_ENABLE([sysfs],
+    [  --enable-sysfs          build sysfs plugin [default=no]],
+    [if test "x$enableval" = "xyes"; then
+        if test "x$have_sysfs" = "xyes"; then
+            PLUGINS="$PLUGINS sysfs"
+        else
+            echo "************************************************************"
+            echo "* libsysfs not found!"
+            echo "* Can't build sysfs support without libsysfs!"
+            echo "* please download and install the latest version of the software"
+            echo "* from http://linux-diag.sf.net"
+            echo "************************************************************"
+            exit 1
+        fi
+    fi])
 
 dnl plugin replacement stuff
 
@@ -185,6 +203,7 @@ AC_CONFIG_FILES([openhpi.spec
         src/plugins/dummy/Makefile
         src/plugins/watchdog/Makefile
         src/plugins/ipmi/Makefile
+        src/plugins/sysfs/Makefile
         docs/Makefile
         docs/hld/Makefile
         examples/Makefile
